/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || 'https://xsave.app',
  generateRobotsTxt: true,
  autoLastmod: false,
  // The transform function allows us to modify the sitemap entries
  // that next-sitemap generates automatically. We'll use it to add
  // the 'x-default' hreflang tag, which is a best practice for SEO.
  transform: (config, path) => {
    // The `alternateRefs` array is automatically generated by next-sitemap
    // based on the i18n settings in `next.config.js`.
    const alternateRefs = config.alternateRefs ?? [];

    // The 'x-default' hreflang should point to the default language version of the page.
    // In Next.js i18n routing, this is the URL without a locale prefix.
    alternateRefs.unshift({
      href: config.siteUrl + path,
      hreflang: 'x-default',
    });

    return {
      loc: path, // next-sitemap will resolve this to the full URL
      changefreq: config.changefreq,
      priority: config.priority,
      lastmod: config.lastmod,
      alternateRefs: alternateRefs,
    };
  },
};